steps:
  # Step 1: Install dependencies (if needed) 
  - name: 'python:3.11'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt']

  # Step 2: Deploy the Cloud Function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - '${_ENV}-init-search-twilio-bland'  # Replace with your function name
      - '--entry-point'
      - 'main'  # Replace with your function's entry point
      - '--runtime'
      - 'python311'  # Replace with your function's runtime environment
      - '--allow-unauthenticated'  # Optional based on your authentication needs
      - '--region'
      - 'nam5'
      - '--gen2'
      - '--set-env-vars'  
      - 'deployment_env=${_ENV}'  # Define your key-value pairs
      - '--trigger-event-filters=type=google.cloud.firestore.document.v1.written'
      - '--trigger-event-filters=database=(default)'
      - '--trigger-event-filters-path-pattern=document=${_ENV}_search_request/{search_request_uuid}'

substitutions:
  _ENV: 'dev'
timeout: '1600s'  # Optional: Adjust as necessary for the complexity of the deployment
